### ISSUE TITLE
Ruby template refactoring

### ISSUE THREAD

**Issue by noraj** [h3xstream/http-script-generator#30]
- [x] #29 remove `require "uri"` because it's already included by `require "net/http"`
    - `require 'net/http'` This will also require 'uri' so you don't need to require it separately. [Ref](https://ruby-doc.org/stdlib-2.7.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Simple+Examples)
- [x] #29 remove `require 'openssl'` because it's already included by `require "net/http"`
    - In previous versions of Ruby you would need to require 'net/https' to use HTTPS. This is no longer true. [Ref](https://ruby-doc.org/stdlib-2.7.1/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-HTTPS) same for openssl
- [ ] multipart refactor
- [x] #29 rubocop-like better styling
    - prefer single quote over double quote when no string interpolation needed
    - space between operators
